server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/pigletLet/myconfig
          username: pigletLet
          password: 129329Sun
          search-paths: schedule
      fail-fast: false



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/

